/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppLeaderboardRouteImport } from './routes/app/leaderboard'
import { Route as AppMyFarmingRouteImport } from './routes/app/my-farming'
import { Route as AppPortfolioRouteImport } from './routes/app/portfolio'
import { Route as AppFarmerIdRouteImport } from './routes/app/farmer/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMyFarmingRoute = AppMyFarmingRouteImport.update({
  id: '/my-farming',
  path: '/my-farming',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmerIdRoute = AppFarmerIdRouteImport.update({
  id: '/farmer/$id',
  path: '/farmer/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-farming': typeof AppMyFarmingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/farmer/$id': typeof AppFarmerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-farming': typeof AppMyFarmingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app': typeof AppIndexRoute
  '/app/farmer/$id': typeof AppFarmerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/my-farming': typeof AppMyFarmingRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/': typeof AppIndexRoute
  '/app/farmer/$id': typeof AppFarmerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/chat'
    | '/app/leaderboard'
    | '/app/my-farming'
    | '/app/portfolio'
    | '/app/'
    | '/app/farmer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/app/leaderboard'
    | '/app/my-farming'
    | '/app/portfolio'
    | '/app'
    | '/app/farmer/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/chat'
    | '/app/leaderboard'
    | '/app/my-farming'
    | '/app/portfolio'
    | '/app/'
    | '/app/farmer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-farming': {
      id: '/app/my-farming'
      path: '/my-farming'
      fullPath: '/app/my-farming'
      preLoaderRoute: typeof AppMyFarmingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farmer/$id': {
      id: '/app/farmer/$id'
      path: '/farmer/$id'
      fullPath: '/app/farmer/$id'
      preLoaderRoute: typeof AppFarmerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMyFarmingRoute: typeof AppMyFarmingRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFarmerIdRoute: typeof AppFarmerIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMyFarmingRoute: AppMyFarmingRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppIndexRoute: AppIndexRoute,
  AppFarmerIdRoute: AppFarmerIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
